// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'base_client/query_result.dart';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'sync.dart';
import 'value.dart';
part 'dart.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `connected_client`, `handle_direct_function_result`, `internal_action`, `internal_mutation`, `internal_set_auth_callback`, `internal_set_auth`, `internal_subscribe`, `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`, `from`

/// Initializes logging for [MobileConvexClient] and its dependencies.
///
/// Call this once early in your application's lifecycle.
void initConvexLogging() => RustLib.instance.api.crateDartInitConvexLogging();

BTreeMapStringValue hashmapToBtreemap({required Map<String, Value> hashmap}) =>
    RustLib.instance.api.crateDartHashmapToBtreemap(hashmap: hashmap);

Map<String, Value> btreemapToHashmap({required BTreeMapStringValue btreemap}) =>
    RustLib.instance.api.crateDartBtreemapToHashmap(btreemap: btreemap);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BTreeMap < String , String >>>
abstract class BTreeMapStringString implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartAuthTokenFetcher>>
abstract class DartAuthTokenFetcher implements RustOpaqueInterface {
  factory DartAuthTokenFetcher({
    required FutureOr<AuthenticationToken> Function(bool) fetcher,
  }) => RustLib.instance.api.crateDartDartAuthTokenFetcherNew(fetcher: fetcher);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartQuerySubscriber>>
abstract class DartQuerySubscriber
    implements RustOpaqueInterface, QuerySubscriber {
  factory DartQuerySubscriber({
    required BoxFnFunctionResultDartFnFutureResult onUpdate,
  }) =>
      RustLib.instance.api.crateDartDartQuerySubscriberNew(onUpdate: onUpdate);

  @override
  Future<void> onUpdate({required FunctionResult value});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartWebSocketStateSubscriber>>
abstract class DartWebSocketStateSubscriber implements RustOpaqueInterface {
  factory DartWebSocketStateSubscriber({
    required FutureOr<void> Function(WebSocketState) onStateChange,
  }) => RustLib.instance.api.crateDartDartWebSocketStateSubscriberNew(
    onStateChange: onStateChange,
  );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileConvexClient>>
abstract class MobileConvexClient implements RustOpaqueInterface {
  /// Executes an action on the Convex backend.
  Future<Value> action({
    required String name,
    required BTreeMapStringValue args,
  });

  /// Executes a mutation on the Convex backend.
  Future<Value> mutation({
    required String name,
    required BTreeMapStringValue args,
  });

  /// Creates a new [MobileConvexClient].
  ///
  /// The internal [ConvexClient] doesn't get created/connected until the
  /// first public method call that hits the Convex backend.
  ///
  /// The `client_id` should be a string representing the name and version of
  /// the foreign client.
  ///
  /// Optionally pass a [DartWebSocketStateSubscriber] to receive connection
  /// state updates (`Connecting` / `Connected`).
  factory MobileConvexClient({
    required String deploymentUrl,
    required String clientId,
    DartWebSocketStateSubscriber? webSocketStateSubscriber,
  }) => RustLib.instance.api.crateDartMobileConvexClientNew(
    deploymentUrl: deploymentUrl,
    clientId: clientId,
    webSocketStateSubscriber: webSocketStateSubscriber,
  );

  /// Executes a query on the Convex backend.
  Future<Value> query({
    required String name,
    required BTreeMapStringValue args,
  });

  /// Provide an OpenID Connect ID token to be associated with this client.
  ///
  /// Doing so will share that information with the Convex backend and a valid
  /// token will give the backend knowledge of a logged in user.
  ///
  /// Passing [None] for the token will disassociate a previous token,
  /// effectively returning to a logged out state.
  Future<void> setAuth({String? token});

  /// Set an auth token fetcher callback for use when calling Convex
  /// functions.
  ///
  /// The callback is invoked immediately (with `force_refresh=false`) and
  /// again on every websocket reconnect (with `force_refresh=true`),
  /// allowing dynamic token refresh.
  ///
  /// Pass `None` to clear the callback and log out.
  Future<void> setAuthCallback({DartAuthTokenFetcher? fetcher});

  /// Subscribe to updates to a query against the Convex backend.
  ///
  /// The [QuerySubscriber] will be called back with initial query results and
  /// it will continue to get called as the underlying data changes.
  ///
  /// The returned [SubscriptionHandle] can be used to cancel the
  /// subscription.
  Future<SubscriptionHandle> subscribe({
    required String name,
    required BTreeMapStringValue args,
    required FutureOr<void> Function(FunctionResult) onUpdate,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SubscriptionHandle>>
abstract class SubscriptionHandle implements RustOpaqueInterface {
  /// Cancels the subscription by sending a cancellation signal.
  void cancel();
}

abstract class QuerySubscriber {
  /// Called when a new update is received
  Future<void> onUpdate({required FunctionResult value});
}

@freezed
sealed class AuthenticationToken with _$AuthenticationToken {
  const AuthenticationToken._();

  /// Admin key issued by a KeyBroker, potentially acting as a user.
  const factory AuthenticationToken.admin(
    String field0, [
    UserIdentityAttributes? field1,
  ]) = AuthenticationToken_Admin;

  /// OpenID Connect JWT
  const factory AuthenticationToken.user(String field0) =
      AuthenticationToken_User;

  /// Logged out.
  const factory AuthenticationToken.none() = AuthenticationToken_None;
}

@freezed
sealed class ClientError with _$ClientError implements FrbException {
  const ClientError._();

  /// An internal error within the mobile Convex client.
  const factory ClientError.internalError({
    /// A generic error message from the server.
    required String msg,
  }) = ClientError_InternalError;

  /// An application-specific error from a remote Convex backend function.
  const factory ClientError.convexError({
    /// The ConvexError passed from the server to the client.
    required ConvexError err,
  }) = ClientError_ConvexError;

  /// An unexpected server-side error from a remote Convex function.
  const factory ClientError.serverError({
    /// A generic error message from the server.
    required String msg,
  }) = ClientError_ServerError;
}

class UserIdentifier {
  final String field0;

  const UserIdentifier({required this.field0});

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserIdentifier &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

class UserIdentityAttributes {
  final UserIdentifier tokenIdentifier;
  final String? issuer;
  final String? subject;
  final String? name;
  final String? givenName;
  final String? familyName;
  final String? nickname;
  final String? preferredUsername;
  final String? profileUrl;
  final String? pictureUrl;
  final String? websiteUrl;
  final String? email;
  final bool? emailVerified;
  final String? gender;
  final String? birthday;
  final String? timezone;
  final String? language;
  final String? phoneNumber;
  final bool? phoneNumberVerified;
  final String? address;

  /// Stored as RFC3339 string
  final String? updatedAt;
  final BTreeMapStringString customClaims;

  const UserIdentityAttributes({
    required this.tokenIdentifier,
    this.issuer,
    this.subject,
    this.name,
    this.givenName,
    this.familyName,
    this.nickname,
    this.preferredUsername,
    this.profileUrl,
    this.pictureUrl,
    this.websiteUrl,
    this.email,
    this.emailVerified,
    this.gender,
    this.birthday,
    this.timezone,
    this.language,
    this.phoneNumber,
    this.phoneNumberVerified,
    this.address,
    this.updatedAt,
    required this.customClaims,
  });

  @override
  int get hashCode =>
      tokenIdentifier.hashCode ^
      issuer.hashCode ^
      subject.hashCode ^
      name.hashCode ^
      givenName.hashCode ^
      familyName.hashCode ^
      nickname.hashCode ^
      preferredUsername.hashCode ^
      profileUrl.hashCode ^
      pictureUrl.hashCode ^
      websiteUrl.hashCode ^
      email.hashCode ^
      emailVerified.hashCode ^
      gender.hashCode ^
      birthday.hashCode ^
      timezone.hashCode ^
      language.hashCode ^
      phoneNumber.hashCode ^
      phoneNumberVerified.hashCode ^
      address.hashCode ^
      updatedAt.hashCode ^
      customClaims.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserIdentityAttributes &&
          runtimeType == other.runtimeType &&
          tokenIdentifier == other.tokenIdentifier &&
          issuer == other.issuer &&
          subject == other.subject &&
          name == other.name &&
          givenName == other.givenName &&
          familyName == other.familyName &&
          nickname == other.nickname &&
          preferredUsername == other.preferredUsername &&
          profileUrl == other.profileUrl &&
          pictureUrl == other.pictureUrl &&
          websiteUrl == other.websiteUrl &&
          email == other.email &&
          emailVerified == other.emailVerified &&
          gender == other.gender &&
          birthday == other.birthday &&
          timezone == other.timezone &&
          language == other.language &&
          phoneNumber == other.phoneNumber &&
          phoneNumberVerified == other.phoneNumberVerified &&
          address == other.address &&
          updatedAt == other.updatedAt &&
          customClaims == other.customClaims;
}
