// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The state of the Convex WebSocket connection
enum WebSocketState {
  /// The WebSocket is open and connected
  connected,

  /// The WebSocket is closed and connecting/reconnecting
  connecting,
}
